name: Bug Report
description: File a bug report for the Vorel App
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you experiencing the bug on?
      options:
        - Desktop / Laptop
        - Raspberry Pi (For TV)
        - Orange Pi (For TV)
        - Android
        - IOS
        - Other
    validations:
      required: true
      
  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using? (For Raspberry Pi / Orange Pi, specify model and OS)
      placeholder: "iPhone 13, Samsung Galaxy S22, etc. (For Desktop/Laptop, specify OS)"
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem