name: Feature Request
description: Suggest an idea for the Vorel App
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
      
  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - UI/UX Improvement
        - New Functionality
        - Performance Enhancement
        - Integration Request
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) is this feature for?
      multiple: true
      options:
        - Mobile
        - Desktop/Laptop
        - Raspberry Pi (For TV)
        - Orange Pi (For TV)
        - All Platforms
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: Spsific Device? (For Raspberry Pi / Orange Pi, specify model and OS, For Desktop/Laptop, specify OS)
      placeholder: "iPhone 13, Samsung Galaxy S22, etc. (For Desktop/Laptop, specify OS)"
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: false
      
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true
      
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would this feature be useful to you or other users?
      placeholder: Explain how this feature would benefit users of the app
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: Are there any alternative solutions or features you've considered?
    validations:
      required: false
      
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Add any other context, references, or screenshots about the feature request here